# Generated by Django 6.0.2 on 2026-02-17 18:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('file', models.FileField(upload_to='files/%Y/%m/%d/', validators=[core.models.validate_document_file], verbose_name='Файл')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file_size', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Размер файла (байты)')),
                ('file_type', models.CharField(blank=True, editable=False, max_length=50, verbose_name='Тип файла')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/', validators=[core.models.validate_image_file], verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt текст')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Ширина (пиксели)')),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Высота (пиксели)')),
                ('file_size', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Размер файла (байты)')),
                ('file_type', models.CharField(blank=True, editable=False, max_length=50, verbose_name='Тип файла')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-created_at'],
            },
        ),
    ]
